on:
  push:
  pull_request_target:
jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olivr/copybara-action@v1.2.3
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          custom_config: copy.bara.sky